### PR TITLE
Refactor build js using new stdlib rules

### PR DESCRIPTION
**Pull request by ShuoYu-bc**
# changelog
Refactored the build scripts using new version of `bldz` standard library.
- **WORKSPACEZ.js** delete unused allocation function and two rule functions
- **BUILDZ.js** clear code, add version check
- **COBOL/BUILDZ.js** rewrite build script to use new bldz rules, clear code.
- Delete script files which don't use anymore after introduce the new rules.

**_NOTE:_**  `bldz` should upgrade to at least **1.42.3**.  `syncz`  should upgrade to **1.19.1**

### CODE REVIEW

**Review by jirimosinger — APPROVED** [review]
LGTM but as @ShuoYu-bc said - `bldz` definitely needs to be updated on the `MINI` before this is merged and it would be nice to have `syncz` updated in the workshop environment itself as well (however, we don't have permissions to even see that [repo](https://github.com/workshopdemos/sandbox-env) so we can't create PR over there)

**Comment by ogonch** [comment]
> LGTM but as @ShuoYu-bc said - `bldz` definitely needs to be updated on the `MINI` before this is merged and it would be nice to have `syncz` updated in the workshop environment itself as well (however, we don't have permissions to even see that [repo](https://github.com/workshopdemos/sandbox-env) so we can't create PR over there)

@sandeep-sirivolu please help with the update of syncz and bldz binaries.

**Comment by VitGottwald** [comment]
Thank you @ShuoYu-bc  and @jirimosinger . There is a workshop taking place on Monday. We will do the upgrade and testing Monday morning. Thank you for your patience.

**Comment by VitGottwald** [comment]
Thank you @ShuoYu-bc and @jirimosinger this was very helpful. We completed the upgrade and tested the debug scenario. All seems to work fine.

The only think that was missing was the PROFILE allocation. I added it back. Do you have scripts for that in the standard library?

**Comment by ShuoYu-bc** [comment]
> Thank you @ShuoYu-bc and @jirimosinger this was very helpful. We completed the upgrade and tested the debug scenario. All seems to work fine.
> 
> The only think that was missing was the PROFILE allocation. I added it back. Do you have scripts for that in the standard library?

Oh, sorry for PROFILE allocation deleted, didn't find anywhere to use it from the context, thought it was which one un-used:) Thanks for add it back.
We didn't integrated PROFILE  allocation in the `intertest` rules, but the function `files.ds.alloc` still is a API comes from standard library.

**Comment by VitGottwald** [comment]
PROFILE is needed during a debugging session - it records and maintains the session metadata and user settings. So it has to exists in order to start a debugging session.

**Comment by jirimosinger** [comment]
> PROFILE is needed during a debugging session - it records and maintains the session metadata and user settings. So it has to exists in order to start a debugging session.

This is interesting! The dataset must have been already allocated when we tested the environment because we didn't run into any issues when we were testing the VS Code Debug extension.

Anyway, glad you could figure it out and thanks for sharing how the `PROFILE` is used

**Comment by ShuoYu-bc** [comment]
Oh, I just found the branch already deleted :)
We also should add three opts back which are not default in the "intertest" rules for COBOL compiling.
```
"APOST",
"RENT",
"LINECOUNT(60)"
```
Just talked to Danko, and knew that if the` LINECOUNT(60)` option is missing would cause issues for extension. I'll create a new branch and add it back.

**Pull request merged**
